services:
  webserver:
    image: nodeserver:v1
    build: .
    develop:
      watch:
         - action: sync+restart
           path: .
           target: /app

  nginx:
    image: nginx:v1
    ports:
      - 80:80
   

  db:
    image: postgres:17.4-alpine3.21
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=qwer1234
    
    

networks:
  mynet1:
  mynet2:

