services:
  webserver:
    image: nodeserver:v1
    networks:
      - mynet1
      - mynet2

  nginx:
    image: nginx:v1
    ports:
      - 80:80
    networks:
      - mynet1
    restart: always

  db:
    image: postgres:17.4-alpine3.21
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=qwer1234
    networks:
      - mynet2
    volumes:
      - :/var/lib/psotgresql/data

networks:
  mynet1:
  mynet2:

volumes:
  postgres_vol:
    external: true