services:
  webserver:
    image: nodeserver:v1
    ports:
      - 8080:8080
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 3
    # environment:
    #   - name=value

  nginx:
    image: nginx:v1
    ports:
      - 80:80
    # environment:
    #   - name=value

  db:
  image: postgres:17.4-alpine3.21
  environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=qwer1234